### ISSUE TITLE
name undefined in shared.js 

### ISSUE THREAD

**Issue by Nfinding** [onebay/vite-plugin-imp#10]
**Describe the bug** 
> [ant-design-vue] get error [vite] Internal server error: Cannot read property 'name' of undefined
   error in node_modules/vite-plugin-imp/dist/shared.js:55:95
   const name = (_a = item) === null || _a === void 0 ? void 0 :  _a.imported.name;

**Libarary Info(please complete the following information):**
   Libarary: [vite]
 - Version [2.3.0]
   Libarary: [ant-design-vue]
 - Version [2.1.6]
 Libarary: [vite-plugin-imp]
 - Version [2.0.7]

**Comment by psaren** [comment]
You should show more details, such as your vite.config.js and what components you import from ant-design-vue.
Can you provide a minimal repo to reproduce this issue?

**Comment by Nfinding** [comment]
> You should show more details, such as your vite.config.js and what components you import from ant-design-vue.
> Can you provide a minimal repo to reproduce this issue?

**Comment by Nfinding** [comment]
the error from:
when use antd as 'import Antd from 'ant-design-vue';'
c (don‘t have imported, so export error in share.js:55:95 const name = (_a = item) === null || _a === void 0 ? void 0 : _a.imported.name;)
Node {
  type: 'ImportDefaultSpecifier',
  start: 67,
  end: 71,
  loc: SourceLocation {
    start: Position { line: 3, column: 7 },
    end: Position { line: 3, column: 11 },
    filename: undefined,
    identifierName: undefined
  },
  range: undefined,
  leadingComments: undefined,
  trailingComments: undefined,
  innerComments: undefined,
  extra: undefined,
  local: Node {
    type: 'Identifier',
    start: 67,
    end: 71,
    loc: SourceLocation {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: 'Antd'
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    name: 'Antd'
  }
}
when use antd as 'import { Input,Button }  from 'ant-design-vue';'
share.js get item is(no error)
Node {
  type: 'ImportSpecifier',
  start: 75,
  end: 81,
  loc: SourceLocation {
  start: Position {
  line: 3,
  column: 15 
},
end: Position {
  line: 3,
  column: 21 
},
filename: undefined,
identifierName: undefined
},
range: undefined,
leadingComments: undefined,
trailingComments: undefined,
innerComments: undefined,
extra: undefined,
imported: Node {
  type: 'Identifier',
  start: 75,
  end: 81,
  loc: SourceLocation {
  start: [
  Position],
  end: [
  Position],
  filename: undefined,
  identifierName: 'Button'
},
range: undefined,
leadingComments: undefined,
trailingComments: undefined,
innerComments: undefined,
extra: undefined,
name: 'Button'
},
local: Node {
  type: 'Identifier',
  start: 75,
  end: 81,
  loc: SourceLocation {
  start: [
  Position],
  end: [
  Position],
  filename: undefined,
  identifierName: 'Button'
},
range: undefined,
leadingComments: undefined,
trailingComments: undefined,
innerComments: undefined,
extra: undefined,
name: 'Button'
}
}

**Comment by psaren** [comment]
The Information you provide a little hard to read.
Maybe you should reference the demo in this repo.
For example:
https://github.com/onebay/vite-plugin-imp/blob/ee24216fdf56b5e7ef2939b8831b8e62cd59341a/demo/vite2-demo/src/components/AntDesignVue.vue#L16-L24

And make sure your vite-plugin-imp config is same as this demo.

If you still have this issue, please provide a minimal repo to reproduce!

**Comment by Nfinding** [comment]
## issue: An error occurred while importing the entire AntD library
[](https://github.com/Nfinding/hulk/blob/master/src/main.ts)

**Comment by psaren** [comment]
If you use default import
``` js
import Antd from 'ant-design-vue';
```
You don't need to use vite-plugin-imp, you  just need:
``` js
import 'ant-design-vue/dist/antd.css';
```
Just like the antd-design-vue office document:
![image](https://user-images.githubusercontent.com/18643034/123059888-cdc07300-d43c-11eb-9e9c-c302086e00b5.png)

You should use vite-plugin-imp only in named import.
For example: 
``` js
import { Button, message } from 'ant-design-vue';
```
