### ISSUE TITLE
ant-design's component "DatePicker" not working when use the plugin 

### ISSUE THREAD

**Issue by PerishCode** [onebay/vite-plugin-imp#13]
**Describe the bug**

   Library : vite-plugin-imp
   Version : 2.0.9 

**To Reproduce**

https://codesandbox.io/s/broken-smoke-1pk50

**Expected behavior**

There should be some response when I click on the date cell, but I got nothing.

**Additional context**

If I import antd.css globally like 
```
import "antd/dist/antd.css"
```
then it doesn't matter whether I use the plugin or not, DataPicker works fine.

**Comment by psaren** [comment]
antd should be use like: 
```ts
vitePluginImp({
  libList: [
    {
      libName: 'antd',
      style: (name) => `antd/es/${name}/style/css.js`
    }
  ]
})
```
https://codesandbox.io/s/objective-cloud-o02fh?file=/vite.config.ts

**Comment by PerishCode** [comment]
Thanks a lot , it works well. ^_^
