### ISSUE TITLE
Does the library not support Ant-design ！！！

### ISSUE THREAD

**Issue by wiscgazf** [onebay/vite-plugin-imp#16]
Rollup failed to resolve import "antd/Slider" from "xxx/xx/xx/xx.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by wiscgazf** [comment]
libarary: [antd](https://ant.design/index-cn)
version:  4.16.13

**Comment by psaren** [comment]
@wiscgazf 
**To Reproduce**
Steps to reproduce the behavior:  
Paste your code here or provide a minimal reproduce repo link.

**Comment by wiscgazf** [comment]
Sorry, that's my problem。

wrong usage：
`
vitePluginImp({
            libList: [
                {
                    libName: 'lodash',
                    libDirectory: '',
                    camel2DashComponentName: false,
                    style: () => {
                        return false;
                    }
                },
                {
                    libName: 'antd',
                    style(name) {
                        return `antd/es/${name}/style/**index.js**`
                    }
                }
            ]
        })
`

Proper use：
`
vitePluginImp({
      libList: [
        {
          libName: 'lodash',
          libDirectory: '',
          camel2DashComponentName: false,
          style: () => {
            return false
          },
        },
        {
          libName: 'antd',
          style(name) {
            return `antd/es/${name}/style/**index.css**`
          },
        },
      ],
    }),
`

**Comment by wiscgazf** [comment]
Thank you for your answer

**Comment by psaren** [comment]
Welcome to discuss, but you need to provide enough information next time.
Close this issue now.
