### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by agileago** [onebay/vite-plugin-imp#21]
https://github.com/onebay/vite-plugin-imp/blob/3fe71b2a9351063f9216abb66d7c3fea51cf6460/src/index.ts#L18

`userConfig?: Partial<ImpConfig>`

this line should have a `?`. when we set plugin `[vitePluginImp()]`

**Comment by psaren** [comment]
Thanks for open this issue, but give it a default value is better:
```ts
 export default function vitePluginImp(userConfig: Partial<ImpConfig> = {}): Plugin {
```
