### ISSUE TITLE
sourcemap is wrong

### ISSUE THREAD

**Issue by agileago** [onebay/vite-plugin-imp#23]
我用了之后，发现sourcemap断点断不上了， 我把代码中的要返回的map手动置成null, 就正常了，最好提供一个选型配置一下是否要返回sourcemap

https://github.com/agileago/fe-template

**Comment by psaren** [comment]
> 我用了之后，发现sourcemap断点断不上了， 我把代码中的要返回的map手动置成null, 就正常了，最好提供一个选型配置一下是否要返回sourcemap
> 
> https://github.com/agileago/fe-template

当然可以提供这个配置
请提供下复现路径，确定下最佳的解决方案

**Comment by agileago** [comment]
1. clone https://github.com/agileago/fe-template
2. `pnpm install`
3. `pnpm run dev`
4. 点击页面的 go to count
5. 在devtools中 `ctrl + p` 搜索 `count.view.tsx` 
6. 然后断点12行会发现断点不上
![2021-12-28 11 59 38](https://user-images.githubusercontent.com/11799110/147526550-7b980d88-5efd-4a3e-ae0c-916e66672645.gif)
7. 把sourcemap手动重置为null, 删除 node_modules下的.vite缓存，重新运行
8. 然后重新断点，会发现一切正常
![2021-12-28 12 02 50](https://user-images.githubusercontent.com/11799110/147526797-85044181-921c-4892-923a-6bdcab35ba19.gif)

**Comment by psaren** [comment]
#24 应该可以解决这个问题

**Comment by agileago** [comment]
perfect.发个版

**Comment by agileago** [comment]
找到原因了么

**Comment by agileago** [comment]
是不是搞错了，我是说传入一个选项 关闭掉插件的sourcemap,不是说关闭整个vite的sourcemap

**Comment by psaren** [comment]
我构建新版本是可以解决了

**Comment by psaren** [comment]
> 是不是搞错了，我是说传入一个选项 关闭掉插件的sourcemap,不是说关闭整个vite的sourcemap

这不会影响vite的sourcemap，只处理了引用库的文件

**Comment by psaren** [comment]
> perfect.发个版

发了

**Comment by GuichiZhao** [comment]
还是不行，禁掉这个插件之后vite的sourcemap就正常了

**Comment by psaren** [comment]
> 还是不行，禁掉这个插件之后vite的sourcemap就正常了

提供下复现仓库/在线demo吧
