### ISSUE TITLE
[vite-plugin-imp] antd/es/*/style is not found!

### ISSUE THREAD

**Issue by BuptStEve** [onebay/vite-plugin-imp#25]
If you set `root` https://vitejs.dev/config/#root

![image](https://user-images.githubusercontent.com/11501493/148013630-7562cdd9-c1d8-42e2-ae03-689252f9d080.png)

Maybe don't pass `viteConfig.root` will fix it...
https://github.com/onebay/vite-plugin-imp/blob/45602cb994219854f1a505b2521bb5cfdaf19cda/src/index.ts#L63

**Comment by psaren** [comment]
Please provide a minimal reproduce from codesandbox

**Comment by BuptStEve** [comment]
https://codesandbox.io/s/dawn-bash-bsq8x?file=/src/App.jsx

**Comment by BuptStEve** [comment]
![image](https://user-images.githubusercontent.com/11501493/148940950-080726fa-420b-4cce-b1c1-4a7c0509fe29.png)
