### ISSUE TITLE
How about icon components import ? like arcod

### ISSUE THREAD

**Issue by zhoujinfu** [onebay/vite-plugin-imp#29]
`@arco-design/web-react/icon` do not support dynamic import out of box with this plugin.

And we should add extra libList to support it, if this plugin support every modern UI frameworks. (antd, arcod, element, etc.)

Why not support icon components ?

```ts
vitePluginImp({
    libList: [
      {
        libName: '@arco-design/web-react/icon',
        libDirectory: 'react-icon',
        camel2DashComponentName: false,
      }
    ],
  }),
```

**Comment by psaren** [comment]
Trying to cover every UI frameworks is a long-term maintenance work（There are always new popular frameworks born） 😆 
I will try my best to covey libraries as many as possible

If you want a libraries work built-in with this plugin, you are welcome to create a PR ❤️

**Comment by zhoujinfu** [comment]
OK, so anyone else should take more care about **arcod** for some components/modules. such as `@arco-design/web-react/icon`, `@arco-design/web-react/ConfigProvider`, etc.
