### ISSUE TITLE
Missing semicolon causes build to fail

### ISSUE THREAD

**Issue by itlangzi** [onebay/vite-plugin-imp#32]
v2.1.4  just upgrade and build fail, the semicolon is missing？
source code at `src/shared.ts` line 68
```js
newImportStatement += `import ${localName} from '${libName}/${libDir}${finalName}'`
```

**Comment by psaren** [comment]
> v2.1.4 just upgrade and build fail, the semicolon is missing？ source code at `src/shared.ts` line 68
> 
> ```js
> newImportStatement += `import ${localName} from '${libName}/${libDir}${finalName}'`
> ```
This is cause by PR #31
Thanks to this issue for letting me know about this bug
I will unpublish V2.1.4, and publish a new version V2.1.5.
