### ISSUE TITLE
支持处理node_modules中的文件

### ISSUE THREAD

**Issue by agileago** [onebay/vite-plugin-imp#34]
**Describe the bug**

有些封装的库没有做打包处理，就是要和项目一起编译，比如我基于 `ant-design-vue`封装了一些高级组件，就是以 `tsx`文件发布的,项目中引用这个库直接被项目的编译工具编译，此时插件未处理按需加载的情况

**Libarary Info(please complete the following information):**
   Libarary: ant-design-vue
 - Version 3

**To Reproduce**
...

**Expected behavior**
支持编译`node_modules`中的文件

**Comment by psaren** [comment]
我觉得如果是发布的库就该由发布方去做编译的工作，这样不需要使用者去配置需要的编译环境(即使不使用vite也可以使用封装的插件，这样才是合理的吧)
你可以在发布时使用vite-plugin-imp插件去做打包

**Comment by agileago** [comment]
是这样的，项目之间共享代码有很多种方式
1. 发布npm包，包独立编译并且使用者使用编译后产物  (一般针对非常通用的库) 代价会产生一些冗余代码， 比如 ts自带的helper函数
2. 使用 git submodule , 使之成为项目的一部分，由项目编译，不会产生冗余文件，但更新起来会比较麻烦
3. 发布源码包，项目编译npm源码，优点自动按需加载，不会产生冗余代码，也容易更新和锁版本

我们团队这里采用的是第三种，直接发布 ts源码包

我们有2中前端模板
1.  webpack的使用 `babel-plugin-import` 按需加载的，没有问题，可以处理
2. vite使用 `vite-plugin-imp`，发现目前没有配置编译 `node_modules` 里面的代码

**Comment by agileago** [comment]
发布源码包很重要的一个原因是因为用到了 `tailwind`, 编译包的话会和项目产生很多冗余类

**Comment by psaren** [comment]
你好，可以提供一个最小可复现仓库来方便深入研究下这个问题吗

**Comment by agileago** [comment]
https://github.com/agileago/imp-issue

```
pnpm install
pnpm dev
```

你应该可以看到 重置按钮和查询按钮样式有问题， 就是 `Space` 组件的样式没有生效，我们封装的组件库是在  `@tmatrix/ui` 里面，入口就是ts文件

https://github.com/onebay/vite-plugin-imp/blob/7ff6f2d92b649bf3706153fae075e0784bcb11c7/src/index.ts#L61

把这个代码判断 `node_module`的地方删了，样式就正常了

**Comment by psaren** [comment]
> 把这个代码判断 `node_module`的地方删了，样式就正常了

当时这么做是为了加快编译速度，因为大多数场景下不需要编译第三方库
如果这样可以解决问题，我的初步方案是在config添加一个参数，
```ts
export interface ImpConfig {
  optimize?: boolean
  libList: LibResolver[]
  /**
   * exclude the library from defaultLibList
   */
  exclude?: string[]
  /**
   * when a style path is not found, don’t show error and give a warning. default `command === 'serve'`
   */
  ignoreStylePathNotFound?: boolean
  /**
   * Skip lib check from node_modules. Default is true
   */
+  skipLibCheck?: boolean
}
```
当需要检测`node_modules`中的文件时将`skipLibCheck`设置为`false`

@agileago 
请看下这样是否能满足你的需求场景

**Comment by agileago** [comment]
是不是加个正则更合适， 就像  https://cli.vuejs.org/zh/config/#transpiledependencies 这样 

```
transpiledependencies: false
transpiledependencies: true
transpiledependencies: ['@tmatrix/ui']
```

**Comment by psaren** [comment]
已经实现了，在 #35
```ts
transpileDependencies?: boolean | Array<string | RegExp>
```
https://github.com/onebay/vite-plugin-imp/blob/438536e51f72708078c9ec209779611959a514e5/src/shared.ts#L170-L180

https://github.com/onebay/vite-plugin-imp/blob/438536e51f72708078c9ec209779611959a514e5/src/index.ts#L60-L65

**Comment by agileago** [comment]
发了么，我测试一下

**Comment by psaren** [comment]
[V2.1.6](https://www.npmjs.com/package/vite-plugin-imp) has been release, the below config should work on your case:
transpileDependencies: true 
transpileDependencies: ['@tmatrix/ui'] 
transpileDependencies: [/@tmatrix/ui/]

**Comment by agileago** [comment]
perfect
