### ISSUE TITLE
is the ignoreStylePathNotFound logic reversed?

### ISSUE THREAD

**Issue by nanxiaobei** [onebay/vite-plugin-imp#37]
https://github.com/onebay/vite-plugin-imp/blob/main/src/shared.ts#L100

Why when "ignore", then check if path exist?

**Comment by psaren** [comment]
ignoreStylePathNotFound = true (default is true in vite serve)
vite-plugin-imp will get a warn message when the style path is not found, and `return ''`, this will avoid error accur.
developer should according to  warn message, adjust the `style` method to return the right style path.

ignoreStylePathNotFound = false
when the style path is not found, it will not check whether style is exist and  return `import ${stylePath}`, and you will get error like `*** MODULE_NOT_FOUND `.

**Comment by nanxiaobei** [comment]
understood, thanks!

**Comment by nanxiaobei** [comment]
currently is that in yarn workspaces:
`require(stylePath)` can not find the file, will warn "xxx is not found!"
`import `${stylePath}`` is fine.

**Comment by psaren** [comment]
pelease provide a minimal repo or an online link(codesandbox/stackblitz) to reproduce the issue.
