### ISSUE TITLE
Doesn't compatible with antd-mobile 5.0 

### ISSUE THREAD

**Issue by leviathan-n** [onebay/vite-plugin-imp#38]
**Describe the bug**
your bug should start with lib, like:   
> [antd-mobile] build failed

**Libarary Info(please complete the following information):**
   Libarary: "antd-mobile": "^5.4.0"

**To Reproduce**
Paste your code here or provide a minimal reproduce repo link.
https://stackblitz.com/edit/vitejs-vite-ixsqtt?file=vite.config.ts

**Expected behavior**

**Error message**
Paste the error message here.
`[vite]: Rollup failed to resolve import "antd-mobile/es/pull-to-refresh/style/css.js" from "src/App.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "antd-mobile/es/pull-to-refresh/style/css.js" from "src/App.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/projects/vitejs-vite-ixsqtt/node_modules/vite/dist/node/chunks/dep-9c153816.js:39242:19)
    at onwarn (/home/projects/vitejs-vite-ixsqtt/node_modules/vite/dist/node/chunks/dep-9c153816.js:39020:13)
    at Object.eval [as onwarn] (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:23129:13)
    at ModuleLoader.handleResolveId (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:22419:26)
    at eval (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:22380:26)`

**Additional context**

**Comment by leviathan-n** [comment]
and I'm wondering that is it possible to convert
`import { someThing } from 'libraryName'` to `import { someThing } from 'libraryName/es/...'`
looks like the plugin hard coded the final output import declaration's pattern according to 
https://github.com/onebay/vite-plugin-imp/blob/fe684300a02e53168160593096b74bcd50b53ef2/src/shared.ts#L67
https://github.com/onebay/vite-plugin-imp/blob/fe684300a02e53168160593096b74bcd50b53ef2/src/shared.ts#L74

**Comment by psaren** [comment]
with antd-mobile v5 you can use:
```js
vitePluginImp({
  libList: [
    {
      libName: 'antd-mobile',
      style: (name) => `antd-mobile/es/components/${name}/${name}.css`
    }
  ]
})
```

**Comment by psaren** [comment]
> and I'm wondering that is it possible to convert `import { someThing } from 'libraryName'` to `import { someThing } from 'libraryName/es/...'` rather than `import someThing from 'libraryName/es/...'` looks like the plugin hard coded the final output import declaration's pattern according to
> 
> https://github.com/onebay/vite-plugin-imp/blob/fe684300a02e53168160593096b74bcd50b53ef2/src/shared.ts#L67
> 
> 
> https://github.com/onebay/vite-plugin-imp/blob/fe684300a02e53168160593096b74bcd50b53ef2/src/shared.ts#L74

This plugin has two main goals：

0: Import style file from a UI framework， when we import a style file  we need `import someThing from 'libraryName/es/...'`.

1: Improve import library like lodash. 
If we use `import { forEach }  from 'lodash'` without this plugin, vite will import a 'lodash/lodash.js' file with a lot of method that we don't use.
lodash method is distributed in different files, so we also need import a js file.

If you want
> convert `import { someThing } from 'libraryName'` to `import { someThing } from 'libraryName/es/...'`

You can just write `import { someThing } from 'libraryName/es/...'` in your source code

Last but not least, if a library is define `module` field in package.json and you are using ESM in your code, it will use `module` file path. 

For example: antd-mobile v5 set `"module": "./es/index.js"`, The file you will eventually import is `antd-mobile /es/index.js`
