### ISSUE TITLE
React antd-mobile  libDirectory 的bug

### ISSUE THREAD

**Issue by xxxxue** [onebay/vite-plugin-imp#40]
**Describe the bug**

源码中 libDirectory 没有填写,  默认是`es`,
而antd-mobile的真正目录因该是`es/components`

**Libarary Info(please complete the following information):**
```
"antd-mobile": "^5.10.3",
"vite-plugin-imp": "^2.1.7",
```
**To Reproduce**
随便使用一个antd-mobile 组件 , 然后 vite build

**Expected behavior**
无需自定义配置 , 即可正常build

**Error message**
> `antd-mobile/es/dialog` 正确的路径应该是 `antd-mobile/es/components/dialog`
```
[vite]: Rollup failed to resolve import "antd-mobile/es/dialog" from "src/pages/product/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Additional context**

我这样自定义libDirectory 后,  解决了该问题.. 
方案来自于 [antd-mobile官网地址](https://mobile.ant.design/zh/guide/import-on-demand)
```
vitePluginImp({ 
      libList: [        
        {
          libName: "antd-mobile",
          libDirectory:"es/components",

          // 下面这个style可能不需要,  需要在 main.tsx 中 引入 import "antd-mobile/es/global";
          //style: (name) => {
          //  return `antd-mobile/es/components/${name}/${name}.css`            
          //}

        }
      ],
    }),
```

**Comment by psaren** [comment]
感谢你提供的issue，我将尽快修复
