### ISSUE TITLE
less的modifyVars无法生效

### ISSUE THREAD

**Issue by he-zhiyong** [onebay/vite-plugin-imp#5]
vite@^2.0.0-beta.64版本下，配置了modifyVars，插件自动引入的less不会生效

![image](https://user-images.githubusercontent.com/23294703/107038016-e6feb500-67f6-11eb-9a6c-56f951dabaab.png)

**Comment by psaren** [comment]
vite-plugin-imp  is work for the repo [vite-less-modify-vars](https://github.com/onebay/vite-less-modify-vars)
you can try it!

**Comment by he-zhiyong** [comment]
It doesn't work with vite@^2.0.0-beta.64 ,This problem may have been fixed in vite@^2.0.0-beta.65. Thanks!

**Comment by ArvinChen9539** [comment]
这个问题说的是主题覆盖吗
如果是element-ui的scss主题覆盖应该怎么配置呢  比如官网上使用babel-plugin-component的话是这样配置
![image](https://user-images.githubusercontent.com/20532645/204694369-a9535265-9e6c-4e00-9d4e-ada33723bd25.png)

**Comment by psaren** [comment]
不是一个问题，可以另开issue @ArvinChen9539
