### ISSUE TITLE
插件不考虑开发环境的sourcemap么，我在开发环境中使用插件，断点不准确

### ISSUE THREAD

**Issue by devie2020** [onebay/vite-plugin-imp#66]
![1655255893695](https://user-images.githubusercontent.com/33315229/173716180-2ea8f4fd-a4c6-4b1b-9d5f-97dbee6bf093.jpg)

**Comment by Tomato-orz** [comment]
这个问题怎么解决啊裂开，how to resolve this problem ,i am going to creazy /(ㄒoㄒ)/~~

**Comment by psaren** [comment]
目前暂时还未找到好的解决方案，如果有方案可以一起探讨或者提个PR

**Comment by Tomato-orz** [comment]
好的感谢回答

**Comment by psaren** [comment]
这个问题应该修复了在V2.3.0

**Comment by StinsonZhao** [comment]
> 这个问题应该修复了在V2.3.0

就算升到了 2.3.0，还是一样的，一旦去掉这个插件断点就正常了

**Comment by ArvinChen9539** [comment]
想哭了  加了这个插件调试的时候打印日志什么的  点进去代码行数是不对的  有希望修复吗o(╥﹏╥)o

**Comment by psaren** [comment]
https://stackblitz.com/edit/vitejs-vite-xviwgy?file=package.json,vite.config.ts,src%2FApp.tsx&terminal=dev
@ArvinChen9539 
点击按钮是可以正常跳转上面的App.tsx 23行的 console.log(count)

**Comment by wolfsilver** [comment]
dev环境关闭sourceMap有点效果
```
build: {
  sourcemap: process.env.NODE_ENV === 'production',
}
```
