### ISSUE TITLE
Can't transform import "lodash"

### ISSUE THREAD

**Issue by tjx666** [onebay/vite-plugin-imp#78]
**Describe the bug**

<img width="963" alt="image" src="https://user-images.githubusercontent.com/41773861/205142977-32aee69a-ddd6-4e76-831f-7db2b4c694c5.png">

> Can't transform import "lodash"

```javascript
vitePluginImp({
    libList: [
        {
            libName: '@xxx/yyy-antd',
            libDirectory: 'es',
            style: (name) => `@xxx/yyy-antd/es/${name}/style/css.js`,
        },
    ],
}),
```

**Libarary Info(please complete the following information):**

```
"vite-plugin-imp": "^2.3.1",
"lodash": "4.17.21"
```

**To Reproduce**

This happen in my company project, which is a large vite + vu2 project.
Two package will use this plugin to tramsform import:

1. lodash
2. @xxx/yyy-antd

**Expected behavior**
 No this warning, or provide an option to supress this warning.

**Comment by psaren** [comment]
Please provide a minimal repo to reproduce this issue.

**Comment by tjx666** [comment]
@psaren When make this warn, should also console.log the file this plugin are transforming

**Comment by tjx666** [comment]
After upgrade rollup and relatived plugins, this issue disapear
