### ISSUE TITLE
It seems that there is no built-in support for @arco-design/web-vue.

### ISSUE THREAD

**Issue by qq326943819** [onebay/vite-plugin-imp#89]
**Additional context**
https://stackblitz.com/edit/vitejs-vite-m9keua?file=src%2FApp.vue,vite.config.ts,src%2Fmain.ts&terminal=dev

**Comment by psaren** [comment]
You should move `@arco-design/web-vue` from devDependencies to dependencies in package.json.
https://stackblitz.com/edit/vitejs-vite-qhnm8j?file=src%2FApp.vue,vite.config.ts,package.json&terminal=dev

**Comment by qq326943819** [comment]
Well, I think it may be necessary to make an explanation in ReadME.
