### ISSUE TITLE
React + antd +vite 按需引入antd 样式，一些组件样式存在问题，比如 Select、DatePicker、Menu

### ISSUE THREAD

**Issue by Jinyang79** [onebay/vite-plugin-imp#9]
**Describe the bug**
React + antd +vite 按需引入antd 样式，一些组件样式存在问题，比如 Select、DatePicker、Menu

**Libarary Info**
"antd": "^4.15.4",
 "vite": "^2.3.4",
 "vite-plugin-imp": "^2.0.7",

**To Reproduce**
```js
import { Select } from 'antd';
// ...
    <Select defaultValue="lucy" style={{ width: 120 }}>
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
      <Option value="Yiminghe">yiminghe</Option>
    </Select>
````

```js
    vitePluginImp({
      libList: [
        {
          libName: 'antd',
          style: (name) => `antd/lib/${name}/style/index.less`,
        }
      ]
    })
```

**Expected behavior**
点击 Select 显示 Option，失去焦点隐藏 Option

** Error message**
点击 Select 显示 Option，失去焦点没有隐藏 Option 如图

[![2uu238.png](https://z3.ax1x.com/2021/06/01/2uu238.png)](https://imgtu.com/i/2uu238)

**Comment by Jinyang79** [comment]
解决了，我改成这个就行了
```js
    vitePluginImp({
      libList: [
        {
          libName: 'antd',
          style: (name) => `antd/es/${name}/style/css.js`
        }
      ]
    })
```

**Comment by psaren** [comment]
对于有内部引用的组件是需要这样去使用

**Comment by AaronWing** [comment]
> 对于有内部引用的组件是需要这样去使用

antd@4.x 还需要这个插件来实现样式按需加载吗？貌似 vite 自身已经实现了吧？

**Comment by psaren** [comment]
@AaronWing  
这应该不可能吧，每个组件库的样式文件都可能存放在不同的地方

**Comment by psaren** [comment]
@AaronWing  
> > 对于有内部引用的组件是需要这样去使用
> 
> [antd@4.x](mailto:antd@4.x) 还需要这个插件来实现样式按需加载吗？貌似 vite 自身已经实现了吧？

这应该不可能吧，每个组件库的样式文件都可能存放在不同的地方
vite自身实现的是组件可以按需加载，但是组件样式还是需要这个插件去按需引用
