### ISSUE TITLE
What about always transform no matter "serve" or "build"

### ISSUE THREAD

**Issue by justforuse** [onebay/vite-plugin-imp#92]
**Describe the bug**

Thanks your work, it is a helpful package

Does this plugin only work under "build"? It maybe useful under development, Or we can add a option, to let user whether always transform the import declaration

**Libarary Info(please complete the following information):**
   Libarary: [name]

**To Reproduce**
Paste your code here or provide a minimal reproduce repo link.

**Expected behavior**

** Error message**
Paste the error message here.

**Additional context**

**Comment by psaren** [comment]
You can just comment out the code for this plugin.
Another way is using the process.env.NODE_ENV 
```tsx
plugins: [
    react(), 
    process.env.NODE_ENV === 'production' ? vitePluginImp() : null
  ],
```

**Comment by justforuse** [comment]
```js
return {
  code: `${importStr};${viteConfig.command === 'serve' ? code : codeRemoveOriginImport}`,
  map: isSourcemap ? sourcemap : null
}
```

Let's clear what I mean. In this code, I want to it return `codeRemoveOriginImport` no matter what the `viteConfig.command` is. so I can get better experience under local development both `serve` and `build`

And the code like this
```js
return {
  code: `${importStr};${(options.always || viteConfig.command === 'serve') ? code : codeRemoveOriginImport}`,
  map: isSourcemap ? sourcemap : null
}
```

**Comment by psaren** [comment]
In order to be compatible with previous versions, this ability needs to be enabled by the developer
Now you can open this in V2.4.0
```ts
vitePluginImp({
   removeOriginImport: true
}),
```
